from .OldBugs.bugnaive import Bug
from .OldBugs.beetle import Beetle
from .OldBugs.fly import Fly
from .OldBugs.lowfly import LowFly
from .OldBugs.dragonfly import DragonFly
from .OldBugs.queenant import QueenAnt
from .OldBugs.ant import WorkerAnt
from .OldBugs.tick import Tick
from .OldBugs.intellibug import IntelliBug
from .bugadv import GrowBug
from .genericbugs import *
